# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '42Events' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 42Events

pod 'Alamofire', '~> 5.2'

  target '42EventsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '42EventsUITests' do
    # Pods for testing
  end

end
